### PR TITLE
Update languages.yml

### PR DESCRIPTION
**Pull request by unlimitedcoder2**

### CODE REVIEW

**Comment by DebitCardz** [comment]
Hey @unlimitedcoder2,
I'm sorry to say but this PR does not follow the contribution guide for Foraging.

I'll be closing this now! Thank you for your time.

**Comment by unlimitedcoder2** [comment]
I'm sory @DebitCardz but I do not see one please could you provide one so that I may request these changes that are in dire need of being made

**Comment by DebitCardz** [comment]
@unlimitedcoder2 the guides for contributing is to make good PRs.
Hope this clears up any misunderstandings!

**Comment by unlimitedcoder2** [comment]
I fail to see the badness in this PR. I'll have you know I have contributed to many large projects with no issues before

**Comment by DebitCardz** [comment]
you.

**Pull request closed without merging**
